export const BANNER = 'api/banner'
export const SONGSHEET = 'api/top/playlist/highquality?before=1503639064232&limit=40'
export const SINGER = 'api/top/artists?offset=0&limit=100'
export const SINGERDETAIL = 'api/artists?id='
export const SONGURL = 'api/song/url?id='
